/* 
 * Sysdig REST API
 *
 * The Sysdig REST API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: info@sysdig.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package swagger

// You will get an errors Obejct when no Authorization header is present. You will get everything (*except* errors) when an Authorization header is present but invalid.
type Errors struct {

	Errors []ModelError `json:"errors,omitempty"`

	Timestamp int64 `json:"timestamp,omitempty"`

	Status int32 `json:"status,omitempty"`

	Error_ string `json:"error,omitempty"`

	Message string `json:"message,omitempty"`

	Path string `json:"path,omitempty"`
}
